name = "Luna's Private Minecraft Modpack"
author = "Luna Nova and Pearl Null"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2ea2dfdfb39ef5310a3779346a5026bbb54dabd73251580ff56d9257dac5bc7"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
