name = "Luna's Private Minecraft Modpack"
author = "Luna Nova and Pearl Null"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33ad75207238aecbb6f881375ab8ba81fed5d13e785d713244996679bffc4743"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
