name = "Luna's Private Minecraft Modpack"
author = "Luna Nova and Pearl Null"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2a06e24f73c8e5182179ac0daf6510d8634ff49a59006b71fa7a745a481eeae"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
